apiVersion: 1

datasources:
  - name: ClickHouse (your-org)
    type: grafana-clickhouse-datasource
    uid: clickhouse-your-org
    jsonData:
      server: clickhouse
      port: 9000
      username: your-org
      defaultDatabase: your-org
      tlsSkipVerify: true
      protocol: native
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    editable: false
    isDefault: false
